### ISSUE TITLE
create form - new member sign-up

### ISSUE THREAD

**Issue by jenjones319** [Gathering401/Gathering-Frontend#14]
required fields in db: 

first name
last name
username
password
birthday
email
phone

https://github.com/Gathering401/Gathering-Backend/blob/master/GatheringAPI/Models/Api/RegisterData.cs

**Comment by ehilst515** [comment]
Registraion form complete

**Comment by ehilst515** [comment]
This is contained in the registration modal. Currently posting to register endpoint.
